import * as symbols from './symbols.js';

export default {
  mainnet: {
    bitcoin: {
      bech32: 'bc',
      bip32: {
        public: 0x0488b21e,
        private: 0x0488ade4,
      },
      bip44: "m/44'/0'/0'",
      bip49: "m/49'/0'/0'",
      bip84: "m/84'/0'/0'",
      bip125: true,
      pubKeyHash: 0x00,
      scriptHash: 0x05,
      wif: 0x80,
      dustThreshold: 546n,
      maxFeePerByte: 5000n,
      rbfFactor: 1.5,
      addressTypes: [symbols.ADDRESS_TYPE_P2WPKH, symbols.ADDRESS_TYPE_P2SH, symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/bitcoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
      factors: [{
        name: 'BTC',
        decimals: 8,
      }, {
        name: 'mBTC',
        decimals: 5,
      }, {
        name: 'μBTC',
        decimals: 2,
      }],
    },
    'bitcoin-cash': {
      bip32: {
        public: 0x0488b21e,
        private: 0x0488ade4,
      },
      bip44: "m/44'/145'/0'",
      pubKeyHash: 0x00,
      scriptHash: 0x05,
      wif: 0x80,
      dustThreshold: 546n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/bitcoin-cash/transaction/${txId}?from=coinwallet',
      minConf: 0,
      factors: [{
        name: 'BCH',
        decimals: 8,
      }, {
        name: 'mBCH',
        decimals: 5,
      }, {
        name: 'μBCH',
        decimals: 2,
      }],
    },
    litecoin: {
      bech32: 'ltc',
      bip32: {
        public: 0x019da462,
        private: 0x019d9cfe,
      },
      bip44: "m/44'/2'/0'",
      bip49: "m/49'/2'/0'",
      bip84: "m/84'/2'/0'",
      pubKeyHash: 0x30,
      scriptHash: 0x32,
      wif: 0xb0,
      dustThreshold: 100000n,
      addressTypes: [symbols.ADDRESS_TYPE_P2WPKH, symbols.ADDRESS_TYPE_P2SH, symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/litecoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
    dogecoin: {
      bip32: {
        public: 0x02facafd,
        private: 0x02fac398,
      },
      bip44: "m/44'/3'/0'",
      pubKeyHash: 0x1e,
      scriptHash: 0x16,
      wif: 0x9e,
      dustThreshold: 1000000n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/dogecoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
    dash: {
      bip32: {
        public: 0x0488b21e,
        private: 0x0488ade4,
      },
      bip44: "m/44'/5'/0'",
      pubKeyHash: 0x4c,
      scriptHash: 0x10,
      wif: 0xcc,
      dustThreshold: 546n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/dash/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
  },
  regtest: {
    bitcoin: {
      bech32: 'bcrt',
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      bip44: "m/44'/1'/0'",
      bip49: "m/49'/1'/0'",
      bip84: "m/84'/1'/0'",
      bip125: true,
      pubKeyHash: 0x6f,
      scriptHash: 0xc4,
      wif: 0xef,
      dustThreshold: 546n,
      maxFeePerByte: 5000n,
      rbfFactor: 1.5,
      addressTypes: [symbols.ADDRESS_TYPE_P2WPKH, symbols.ADDRESS_TYPE_P2SH, symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/bitcoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
      factors: [{
        name: 'BTC',
        decimals: 8,
      }, {
        name: 'mBTC',
        decimals: 5,
      }, {
        name: 'μBTC',
        decimals: 2,
      }],
    },
    'bitcoin-cash': {
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      bip44: "m/44'/1'/0'",
      pubKeyHash: 0x6f,
      scriptHash: 0xc4,
      wif: 0xef,
      dustThreshold: 546n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/bitcoin-cash/transaction/${txId}?from=coinwallet',
      minConf: 0,
      factors: [{
        name: 'BCH',
        decimals: 8,
      }, {
        name: 'mBCH',
        decimals: 5,
      }, {
        name: 'μBCH',
        decimals: 2,
      }],
    },
    litecoin: {
      bech32: 'rltc',
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      bip44: "m/44'/1'/0'",
      bip49: "m/49'/1'/0'",
      bip84: "m/84'/1'/0'",
      pubKeyHash: 0x6f,
      scriptHash: 0x3a,
      wif: 0xef,
      dustThreshold: 100000n,
      addressTypes: [symbols.ADDRESS_TYPE_P2WPKH, symbols.ADDRESS_TYPE_P2SH, symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/litecoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
    dogecoin: {
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      bip44: "m/44'/1'/0'",
      pubKeyHash: 0x6f,
      scriptHash: 0xc4,
      wif: 0xef,
      dustThreshold: 1000000n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/dogecoin/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
    dash: {
      bip32: {
        public: 0x043587cf,
        private: 0x04358394,
      },
      bip44: "m/44'/1'/0'",
      pubKeyHash: 0x8c,
      scriptHash: 0x13,
      wif: 0xef,
      dustThreshold: 546n,
      addressTypes: [symbols.ADDRESS_TYPE_P2PKH],
      txUrl: 'https://blockchair.com/dash/transaction/${txId}?from=coinwallet',
      minConf: 3,
    },
  },
};
